---
services:
  ubuntu_22_04:
    image: sensory-cloud-cpp-sdk:Ubuntu22.04
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.Ubuntu.22.04
  ubuntu_20_04:
    image: sensory-cloud-cpp-sdk:Ubuntu20.04
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.Ubuntu.20.04
  ubuntu_18_04:
    image: sensory-cloud-cpp-sdk:Ubuntu18.04
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.Ubuntu.18.04
  ubuntu_16_04:
    image: sensory-cloud-cpp-sdk:Ubuntu16.04
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.Ubuntu.16.04
  debian_11:
    image: sensory-cloud-cpp-sdk:Debian11
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.Debian.11
  debian_10:
    image: sensory-cloud-cpp-sdk:Debian10
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.Debian.10
  debian_9:
    image: sensory-cloud-cpp-sdk:Debian9
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.Debian.9
  rhel_9:
    image: sensory-cloud-cpp-sdk:RHEL9
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.RHEL.9
  rhel_8:
    image: sensory-cloud-cpp-sdk:RHEL8
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.RHEL.8
  rhel_7:
    image: sensory-cloud-cpp-sdk:RHEL7
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.RHEL.7
  centos_8:
    image: sensory-cloud-cpp-sdk:CentOS8
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.CentOS.8
  centos_7:
    image: sensory-cloud-cpp-sdk:CentOS7
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.CentOS.7
