services:
  # CentOS
  centos_7:
    image: sensory-cloud-cpp-sdk:CentOS7
    build:
      context: .
      dockerfile: Dockerfile.CentOS.7
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  centos_8:
    image: sensory-cloud-cpp-sdk:CentOS8
    build:
      context: .
      dockerfile: Dockerfile.CentOS.8
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  # RHEL
  rhel_7:
    image: sensory-cloud-cpp-sdk:RHEL7
    build:
      context: .
      dockerfile: Dockerfile.RHEL.7
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  rhel_8:
    image: sensory-cloud-cpp-sdk:RHEL8
    build:
      context: .
      dockerfile: Dockerfile.RHEL.8
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  # Debian
  debian_9:
    image: sensory-cloud-cpp-sdk:Debian9
    build:
      context: .
      dockerfile: Dockerfile.Debian.9
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  debian_10:
    image: sensory-cloud-cpp-sdk:Debian10
    build:
      context: .
      dockerfile: Dockerfile.Debian.10
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  debian_11:
    image: sensory-cloud-cpp-sdk:Debian11
    build:
      context: .
      dockerfile: Dockerfile.Debian.11
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  # Ubuntu
  ubuntu_16_04:
    image: sensory-cloud-cpp-sdk:Ubuntu16.04
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu.16.04
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  ubuntu_18_04:
    image: sensory-cloud-cpp-sdk:Ubuntu18.04
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu.18.04
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  ubuntu_20_04:
    image: sensory-cloud-cpp-sdk:Ubuntu20.04
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu.20.04
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
  ubuntu_21_10:
    image: sensory-cloud-cpp-sdk:Ubuntu21.04
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu.21.10
    working_dir: /cpp-sdk
    command: make && find build -name "test*" -exec echo {} \; -exec {} \;
