// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: v1/management/device.proto

#include "sensorycloud/protoc/v1/management/device.pb.h"
#include "sensorycloud/protoc/v1/management/device.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sensory {
namespace api {
namespace v1 {
namespace management {

static const char* DeviceService_method_names[] = {
  "/sensory.api.v1.management.DeviceService/EnrollDevice",
  "/sensory.api.v1.management.DeviceService/GetWhoAmI",
};

std::unique_ptr< DeviceService::Stub> DeviceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DeviceService::Stub> stub(new DeviceService::Stub(channel, options));
  return stub;
}

DeviceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_EnrollDevice_(DeviceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetWhoAmI_(DeviceService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DeviceService::Stub::EnrollDevice(::grpc::ClientContext* context, const ::sensory::api::v1::management::EnrollDeviceRequest& request, ::sensory::api::v1::management::DeviceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sensory::api::v1::management::EnrollDeviceRequest, ::sensory::api::v1::management::DeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EnrollDevice_, context, request, response);
}

void DeviceService::Stub::async::EnrollDevice(::grpc::ClientContext* context, const ::sensory::api::v1::management::EnrollDeviceRequest* request, ::sensory::api::v1::management::DeviceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sensory::api::v1::management::EnrollDeviceRequest, ::sensory::api::v1::management::DeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnrollDevice_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::EnrollDevice(::grpc::ClientContext* context, const ::sensory::api::v1::management::EnrollDeviceRequest* request, ::sensory::api::v1::management::DeviceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnrollDevice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sensory::api::v1::management::DeviceResponse>* DeviceService::Stub::PrepareAsyncEnrollDeviceRaw(::grpc::ClientContext* context, const ::sensory::api::v1::management::EnrollDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sensory::api::v1::management::DeviceResponse, ::sensory::api::v1::management::EnrollDeviceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EnrollDevice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sensory::api::v1::management::DeviceResponse>* DeviceService::Stub::AsyncEnrollDeviceRaw(::grpc::ClientContext* context, const ::sensory::api::v1::management::EnrollDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEnrollDeviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceService::Stub::GetWhoAmI(::grpc::ClientContext* context, const ::sensory::api::v1::management::DeviceGetWhoAmIRequest& request, ::sensory::api::v1::management::DeviceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sensory::api::v1::management::DeviceGetWhoAmIRequest, ::sensory::api::v1::management::DeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetWhoAmI_, context, request, response);
}

void DeviceService::Stub::async::GetWhoAmI(::grpc::ClientContext* context, const ::sensory::api::v1::management::DeviceGetWhoAmIRequest* request, ::sensory::api::v1::management::DeviceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sensory::api::v1::management::DeviceGetWhoAmIRequest, ::sensory::api::v1::management::DeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetWhoAmI_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::GetWhoAmI(::grpc::ClientContext* context, const ::sensory::api::v1::management::DeviceGetWhoAmIRequest* request, ::sensory::api::v1::management::DeviceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetWhoAmI_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sensory::api::v1::management::DeviceResponse>* DeviceService::Stub::PrepareAsyncGetWhoAmIRaw(::grpc::ClientContext* context, const ::sensory::api::v1::management::DeviceGetWhoAmIRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sensory::api::v1::management::DeviceResponse, ::sensory::api::v1::management::DeviceGetWhoAmIRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetWhoAmI_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sensory::api::v1::management::DeviceResponse>* DeviceService::Stub::AsyncGetWhoAmIRaw(::grpc::ClientContext* context, const ::sensory::api::v1::management::DeviceGetWhoAmIRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetWhoAmIRaw(context, request, cq);
  result->StartCall();
  return result;
}

DeviceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::sensory::api::v1::management::EnrollDeviceRequest, ::sensory::api::v1::management::DeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sensory::api::v1::management::EnrollDeviceRequest* req,
             ::sensory::api::v1::management::DeviceResponse* resp) {
               return service->EnrollDevice(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::sensory::api::v1::management::DeviceGetWhoAmIRequest, ::sensory::api::v1::management::DeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sensory::api::v1::management::DeviceGetWhoAmIRequest* req,
             ::sensory::api::v1::management::DeviceResponse* resp) {
               return service->GetWhoAmI(ctx, req, resp);
             }, this)));
}

DeviceService::Service::~Service() {
}

::grpc::Status DeviceService::Service::EnrollDevice(::grpc::ServerContext* context, const ::sensory::api::v1::management::EnrollDeviceRequest* request, ::sensory::api::v1::management::DeviceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::GetWhoAmI(::grpc::ServerContext* context, const ::sensory::api::v1::management::DeviceGetWhoAmIRequest* request, ::sensory::api::v1::management::DeviceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sensory
}  // namespace api
}  // namespace v1
}  // namespace management

