// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/management/device.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_v1_2fmanagement_2fdevice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_v1_2fmanagement_2fdevice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "sensorycloud/protoc/common/common.pb.h"
#include "sensorycloud/protoc/validate/validate.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_v1_2fmanagement_2fdevice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_v1_2fmanagement_2fdevice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_v1_2fmanagement_2fdevice_2eproto;
namespace sensory {
namespace api {
namespace v1 {
namespace management {
class DeviceGetWhoAmIRequest;
struct DeviceGetWhoAmIRequestDefaultTypeInternal;
extern DeviceGetWhoAmIRequestDefaultTypeInternal _DeviceGetWhoAmIRequest_default_instance_;
class DeviceResponse;
struct DeviceResponseDefaultTypeInternal;
extern DeviceResponseDefaultTypeInternal _DeviceResponse_default_instance_;
class EnrollDeviceRequest;
struct EnrollDeviceRequestDefaultTypeInternal;
extern EnrollDeviceRequestDefaultTypeInternal _EnrollDeviceRequest_default_instance_;
}  // namespace management
}  // namespace v1
}  // namespace api
}  // namespace sensory
PROTOBUF_NAMESPACE_OPEN
template<> ::sensory::api::v1::management::DeviceGetWhoAmIRequest* Arena::CreateMaybeMessage<::sensory::api::v1::management::DeviceGetWhoAmIRequest>(Arena*);
template<> ::sensory::api::v1::management::DeviceResponse* Arena::CreateMaybeMessage<::sensory::api::v1::management::DeviceResponse>(Arena*);
template<> ::sensory::api::v1::management::EnrollDeviceRequest* Arena::CreateMaybeMessage<::sensory::api::v1::management::EnrollDeviceRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sensory {
namespace api {
namespace v1 {
namespace management {

// ===================================================================

class EnrollDeviceRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sensory.api.v1.management.EnrollDeviceRequest) */ {
 public:
  inline EnrollDeviceRequest() : EnrollDeviceRequest(nullptr) {}
  ~EnrollDeviceRequest() override;
  explicit constexpr EnrollDeviceRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EnrollDeviceRequest(const EnrollDeviceRequest& from);
  EnrollDeviceRequest(EnrollDeviceRequest&& from) noexcept
    : EnrollDeviceRequest() {
    *this = ::std::move(from);
  }

  inline EnrollDeviceRequest& operator=(const EnrollDeviceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnrollDeviceRequest& operator=(EnrollDeviceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnrollDeviceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnrollDeviceRequest* internal_default_instance() {
    return reinterpret_cast<const EnrollDeviceRequest*>(
               &_EnrollDeviceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EnrollDeviceRequest& a, EnrollDeviceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(EnrollDeviceRequest* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnrollDeviceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EnrollDeviceRequest* New() const final {
    return new EnrollDeviceRequest();
  }

  EnrollDeviceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EnrollDeviceRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EnrollDeviceRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const EnrollDeviceRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnrollDeviceRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sensory.api.v1.management.EnrollDeviceRequest";
  }
  protected:
  explicit EnrollDeviceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kDeviceIdFieldNumber = 2,
    kTenantIdFieldNumber = 3,
    kCredentialFieldNumber = 5,
    kClientFieldNumber = 4,
  };
  // string name = 1 [(.validate.rules) = {
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string deviceId = 2 [(.validate.rules) = {
  void clear_deviceid();
  const std::string& deviceid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_deviceid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_deviceid();
  PROTOBUF_MUST_USE_RESULT std::string* release_deviceid();
  void set_allocated_deviceid(std::string* deviceid);
  private:
  const std::string& _internal_deviceid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_deviceid(const std::string& value);
  std::string* _internal_mutable_deviceid();
  public:

  // string tenantId = 3 [(.validate.rules) = {
  void clear_tenantid();
  const std::string& tenantid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_tenantid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_tenantid();
  PROTOBUF_MUST_USE_RESULT std::string* release_tenantid();
  void set_allocated_tenantid(std::string* tenantid);
  private:
  const std::string& _internal_tenantid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tenantid(const std::string& value);
  std::string* _internal_mutable_tenantid();
  public:

  // string credential = 5;
  void clear_credential();
  const std::string& credential() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_credential(ArgT0&& arg0, ArgT... args);
  std::string* mutable_credential();
  PROTOBUF_MUST_USE_RESULT std::string* release_credential();
  void set_allocated_credential(std::string* credential);
  private:
  const std::string& _internal_credential() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_credential(const std::string& value);
  std::string* _internal_mutable_credential();
  public:

  // .sensory.api.common.GenericClient client = 4 [(.validate.rules) = {
  bool has_client() const;
  private:
  bool _internal_has_client() const;
  public:
  void clear_client();
  const ::sensory::api::common::GenericClient& client() const;
  PROTOBUF_MUST_USE_RESULT ::sensory::api::common::GenericClient* release_client();
  ::sensory::api::common::GenericClient* mutable_client();
  void set_allocated_client(::sensory::api::common::GenericClient* client);
  private:
  const ::sensory::api::common::GenericClient& _internal_client() const;
  ::sensory::api::common::GenericClient* _internal_mutable_client();
  public:
  void unsafe_arena_set_allocated_client(
      ::sensory::api::common::GenericClient* client);
  ::sensory::api::common::GenericClient* unsafe_arena_release_client();

  // @@protoc_insertion_point(class_scope:sensory.api.v1.management.EnrollDeviceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr deviceid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tenantid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr credential_;
  ::sensory::api::common::GenericClient* client_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_v1_2fmanagement_2fdevice_2eproto;
};
// -------------------------------------------------------------------

class DeviceResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sensory.api.v1.management.DeviceResponse) */ {
 public:
  inline DeviceResponse() : DeviceResponse(nullptr) {}
  ~DeviceResponse() override;
  explicit constexpr DeviceResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeviceResponse(const DeviceResponse& from);
  DeviceResponse(DeviceResponse&& from) noexcept
    : DeviceResponse() {
    *this = ::std::move(from);
  }

  inline DeviceResponse& operator=(const DeviceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeviceResponse& operator=(DeviceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeviceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeviceResponse* internal_default_instance() {
    return reinterpret_cast<const DeviceResponse*>(
               &_DeviceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DeviceResponse& a, DeviceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DeviceResponse* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeviceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DeviceResponse* New() const final {
    return new DeviceResponse();
  }

  DeviceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DeviceResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeviceResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DeviceResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sensory.api.v1.management.DeviceResponse";
  }
  protected:
  explicit DeviceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kDeviceIdFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string deviceId = 2;
  void clear_deviceid();
  const std::string& deviceid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_deviceid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_deviceid();
  PROTOBUF_MUST_USE_RESULT std::string* release_deviceid();
  void set_allocated_deviceid(std::string* deviceid);
  private:
  const std::string& _internal_deviceid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_deviceid(const std::string& value);
  std::string* _internal_mutable_deviceid();
  public:

  // @@protoc_insertion_point(class_scope:sensory.api.v1.management.DeviceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr deviceid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_v1_2fmanagement_2fdevice_2eproto;
};
// -------------------------------------------------------------------

class DeviceGetWhoAmIRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sensory.api.v1.management.DeviceGetWhoAmIRequest) */ {
 public:
  inline DeviceGetWhoAmIRequest() : DeviceGetWhoAmIRequest(nullptr) {}
  ~DeviceGetWhoAmIRequest() override;
  explicit constexpr DeviceGetWhoAmIRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeviceGetWhoAmIRequest(const DeviceGetWhoAmIRequest& from);
  DeviceGetWhoAmIRequest(DeviceGetWhoAmIRequest&& from) noexcept
    : DeviceGetWhoAmIRequest() {
    *this = ::std::move(from);
  }

  inline DeviceGetWhoAmIRequest& operator=(const DeviceGetWhoAmIRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeviceGetWhoAmIRequest& operator=(DeviceGetWhoAmIRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeviceGetWhoAmIRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeviceGetWhoAmIRequest* internal_default_instance() {
    return reinterpret_cast<const DeviceGetWhoAmIRequest*>(
               &_DeviceGetWhoAmIRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DeviceGetWhoAmIRequest& a, DeviceGetWhoAmIRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DeviceGetWhoAmIRequest* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeviceGetWhoAmIRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DeviceGetWhoAmIRequest* New() const final {
    return new DeviceGetWhoAmIRequest();
  }

  DeviceGetWhoAmIRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DeviceGetWhoAmIRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeviceGetWhoAmIRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DeviceGetWhoAmIRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceGetWhoAmIRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sensory.api.v1.management.DeviceGetWhoAmIRequest";
  }
  protected:
  explicit DeviceGetWhoAmIRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:sensory.api.v1.management.DeviceGetWhoAmIRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_v1_2fmanagement_2fdevice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EnrollDeviceRequest

// string name = 1 [(.validate.rules) = {
inline void EnrollDeviceRequest::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& EnrollDeviceRequest::name() const {
  // @@protoc_insertion_point(field_get:sensory.api.v1.management.EnrollDeviceRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EnrollDeviceRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sensory.api.v1.management.EnrollDeviceRequest.name)
}
inline std::string* EnrollDeviceRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:sensory.api.v1.management.EnrollDeviceRequest.name)
  return _s;
}
inline const std::string& EnrollDeviceRequest::_internal_name() const {
  return name_.Get();
}
inline void EnrollDeviceRequest::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* EnrollDeviceRequest::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* EnrollDeviceRequest::release_name() {
  // @@protoc_insertion_point(field_release:sensory.api.v1.management.EnrollDeviceRequest.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void EnrollDeviceRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:sensory.api.v1.management.EnrollDeviceRequest.name)
}

// string deviceId = 2 [(.validate.rules) = {
inline void EnrollDeviceRequest::clear_deviceid() {
  deviceid_.ClearToEmpty();
}
inline const std::string& EnrollDeviceRequest::deviceid() const {
  // @@protoc_insertion_point(field_get:sensory.api.v1.management.EnrollDeviceRequest.deviceId)
  return _internal_deviceid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EnrollDeviceRequest::set_deviceid(ArgT0&& arg0, ArgT... args) {
 
 deviceid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sensory.api.v1.management.EnrollDeviceRequest.deviceId)
}
inline std::string* EnrollDeviceRequest::mutable_deviceid() {
  std::string* _s = _internal_mutable_deviceid();
  // @@protoc_insertion_point(field_mutable:sensory.api.v1.management.EnrollDeviceRequest.deviceId)
  return _s;
}
inline const std::string& EnrollDeviceRequest::_internal_deviceid() const {
  return deviceid_.Get();
}
inline void EnrollDeviceRequest::_internal_set_deviceid(const std::string& value) {
  
  deviceid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* EnrollDeviceRequest::_internal_mutable_deviceid() {
  
  return deviceid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* EnrollDeviceRequest::release_deviceid() {
  // @@protoc_insertion_point(field_release:sensory.api.v1.management.EnrollDeviceRequest.deviceId)
  return deviceid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void EnrollDeviceRequest::set_allocated_deviceid(std::string* deviceid) {
  if (deviceid != nullptr) {
    
  } else {
    
  }
  deviceid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), deviceid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:sensory.api.v1.management.EnrollDeviceRequest.deviceId)
}

// string tenantId = 3 [(.validate.rules) = {
inline void EnrollDeviceRequest::clear_tenantid() {
  tenantid_.ClearToEmpty();
}
inline const std::string& EnrollDeviceRequest::tenantid() const {
  // @@protoc_insertion_point(field_get:sensory.api.v1.management.EnrollDeviceRequest.tenantId)
  return _internal_tenantid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EnrollDeviceRequest::set_tenantid(ArgT0&& arg0, ArgT... args) {
 
 tenantid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sensory.api.v1.management.EnrollDeviceRequest.tenantId)
}
inline std::string* EnrollDeviceRequest::mutable_tenantid() {
  std::string* _s = _internal_mutable_tenantid();
  // @@protoc_insertion_point(field_mutable:sensory.api.v1.management.EnrollDeviceRequest.tenantId)
  return _s;
}
inline const std::string& EnrollDeviceRequest::_internal_tenantid() const {
  return tenantid_.Get();
}
inline void EnrollDeviceRequest::_internal_set_tenantid(const std::string& value) {
  
  tenantid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* EnrollDeviceRequest::_internal_mutable_tenantid() {
  
  return tenantid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* EnrollDeviceRequest::release_tenantid() {
  // @@protoc_insertion_point(field_release:sensory.api.v1.management.EnrollDeviceRequest.tenantId)
  return tenantid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void EnrollDeviceRequest::set_allocated_tenantid(std::string* tenantid) {
  if (tenantid != nullptr) {
    
  } else {
    
  }
  tenantid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tenantid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:sensory.api.v1.management.EnrollDeviceRequest.tenantId)
}

// .sensory.api.common.GenericClient client = 4 [(.validate.rules) = {
inline bool EnrollDeviceRequest::_internal_has_client() const {
  return this != internal_default_instance() && client_ != nullptr;
}
inline bool EnrollDeviceRequest::has_client() const {
  return _internal_has_client();
}
inline const ::sensory::api::common::GenericClient& EnrollDeviceRequest::_internal_client() const {
  const ::sensory::api::common::GenericClient* p = client_;
  return p != nullptr ? *p : reinterpret_cast<const ::sensory::api::common::GenericClient&>(
      ::sensory::api::common::_GenericClient_default_instance_);
}
inline const ::sensory::api::common::GenericClient& EnrollDeviceRequest::client() const {
  // @@protoc_insertion_point(field_get:sensory.api.v1.management.EnrollDeviceRequest.client)
  return _internal_client();
}
inline void EnrollDeviceRequest::unsafe_arena_set_allocated_client(
    ::sensory::api::common::GenericClient* client) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(client_);
  }
  client_ = client;
  if (client) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sensory.api.v1.management.EnrollDeviceRequest.client)
}
inline ::sensory::api::common::GenericClient* EnrollDeviceRequest::release_client() {
  
  ::sensory::api::common::GenericClient* temp = client_;
  client_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::sensory::api::common::GenericClient* EnrollDeviceRequest::unsafe_arena_release_client() {
  // @@protoc_insertion_point(field_release:sensory.api.v1.management.EnrollDeviceRequest.client)
  
  ::sensory::api::common::GenericClient* temp = client_;
  client_ = nullptr;
  return temp;
}
inline ::sensory::api::common::GenericClient* EnrollDeviceRequest::_internal_mutable_client() {
  
  if (client_ == nullptr) {
    auto* p = CreateMaybeMessage<::sensory::api::common::GenericClient>(GetArenaForAllocation());
    client_ = p;
  }
  return client_;
}
inline ::sensory::api::common::GenericClient* EnrollDeviceRequest::mutable_client() {
  ::sensory::api::common::GenericClient* _msg = _internal_mutable_client();
  // @@protoc_insertion_point(field_mutable:sensory.api.v1.management.EnrollDeviceRequest.client)
  return _msg;
}
inline void EnrollDeviceRequest::set_allocated_client(::sensory::api::common::GenericClient* client) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(client_);
  }
  if (client) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(client));
    if (message_arena != submessage_arena) {
      client = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, client, submessage_arena);
    }
    
  } else {
    
  }
  client_ = client;
  // @@protoc_insertion_point(field_set_allocated:sensory.api.v1.management.EnrollDeviceRequest.client)
}

// string credential = 5;
inline void EnrollDeviceRequest::clear_credential() {
  credential_.ClearToEmpty();
}
inline const std::string& EnrollDeviceRequest::credential() const {
  // @@protoc_insertion_point(field_get:sensory.api.v1.management.EnrollDeviceRequest.credential)
  return _internal_credential();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EnrollDeviceRequest::set_credential(ArgT0&& arg0, ArgT... args) {
 
 credential_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sensory.api.v1.management.EnrollDeviceRequest.credential)
}
inline std::string* EnrollDeviceRequest::mutable_credential() {
  std::string* _s = _internal_mutable_credential();
  // @@protoc_insertion_point(field_mutable:sensory.api.v1.management.EnrollDeviceRequest.credential)
  return _s;
}
inline const std::string& EnrollDeviceRequest::_internal_credential() const {
  return credential_.Get();
}
inline void EnrollDeviceRequest::_internal_set_credential(const std::string& value) {
  
  credential_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* EnrollDeviceRequest::_internal_mutable_credential() {
  
  return credential_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* EnrollDeviceRequest::release_credential() {
  // @@protoc_insertion_point(field_release:sensory.api.v1.management.EnrollDeviceRequest.credential)
  return credential_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void EnrollDeviceRequest::set_allocated_credential(std::string* credential) {
  if (credential != nullptr) {
    
  } else {
    
  }
  credential_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), credential,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:sensory.api.v1.management.EnrollDeviceRequest.credential)
}

// -------------------------------------------------------------------

// DeviceResponse

// string name = 1;
inline void DeviceResponse::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& DeviceResponse::name() const {
  // @@protoc_insertion_point(field_get:sensory.api.v1.management.DeviceResponse.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DeviceResponse::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sensory.api.v1.management.DeviceResponse.name)
}
inline std::string* DeviceResponse::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:sensory.api.v1.management.DeviceResponse.name)
  return _s;
}
inline const std::string& DeviceResponse::_internal_name() const {
  return name_.Get();
}
inline void DeviceResponse::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DeviceResponse::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DeviceResponse::release_name() {
  // @@protoc_insertion_point(field_release:sensory.api.v1.management.DeviceResponse.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DeviceResponse::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:sensory.api.v1.management.DeviceResponse.name)
}

// string deviceId = 2;
inline void DeviceResponse::clear_deviceid() {
  deviceid_.ClearToEmpty();
}
inline const std::string& DeviceResponse::deviceid() const {
  // @@protoc_insertion_point(field_get:sensory.api.v1.management.DeviceResponse.deviceId)
  return _internal_deviceid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DeviceResponse::set_deviceid(ArgT0&& arg0, ArgT... args) {
 
 deviceid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sensory.api.v1.management.DeviceResponse.deviceId)
}
inline std::string* DeviceResponse::mutable_deviceid() {
  std::string* _s = _internal_mutable_deviceid();
  // @@protoc_insertion_point(field_mutable:sensory.api.v1.management.DeviceResponse.deviceId)
  return _s;
}
inline const std::string& DeviceResponse::_internal_deviceid() const {
  return deviceid_.Get();
}
inline void DeviceResponse::_internal_set_deviceid(const std::string& value) {
  
  deviceid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DeviceResponse::_internal_mutable_deviceid() {
  
  return deviceid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DeviceResponse::release_deviceid() {
  // @@protoc_insertion_point(field_release:sensory.api.v1.management.DeviceResponse.deviceId)
  return deviceid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DeviceResponse::set_allocated_deviceid(std::string* deviceid) {
  if (deviceid != nullptr) {
    
  } else {
    
  }
  deviceid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), deviceid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:sensory.api.v1.management.DeviceResponse.deviceId)
}

// -------------------------------------------------------------------

// DeviceGetWhoAmIRequest

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace management
}  // namespace v1
}  // namespace api
}  // namespace sensory

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_v1_2fmanagement_2fdevice_2eproto
