// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: common/common.proto
// Original file comments:
// sensory.api.common
#ifndef GRPC_common_2fcommon_2eproto__INCLUDED
#define GRPC_common_2fcommon_2eproto__INCLUDED

#include "sensorycloud/protoc/common/common.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace sensory {
namespace api {
namespace common {

}  // namespace common
}  // namespace api
}  // namespace sensory


#endif  // GRPC_common_2fcommon_2eproto__INCLUDED
